In [1]:
import os

os.environ["HF_HOME"] = "D:/huggingface_cache"

print("Hugging Face cache set to D drive")

Hugging Face cache set to D drive

In [2]:
import pandas as pd

data = {
    "ticket_id": [
        1,2,3,4,5,6,7,8,9,10
    ],

    "ticket_text": [
        "My internet connection is not working",
        "I forgot my password and cannot login to my account",
        "My payment was declined while making a purchase",
        "The mobile application crashes when I open it",
        "I want to cancel my subscription plan",
        "My order has not arrived yet",
        "I received a damaged product",
        "Someone hacked my account and changed my password",
        "I need help updating my profile details",
        "The website is showing an unexpected error"
    ],

    "category": [
        "Internet Issue",
        "Account Login",
        "Payment Issue",
        "App Problem",
        "Subscription",
        "Delivery Issue",
        "Product Issue",
        "Security",
        "Account Management",
        "Website Error"
    ]
}


df = pd.DataFrame(data)

df

,ticket_id,ticket_text,category
0,1,My internet connection is not working,Internet Issue
1,2,I forgot my password and cannot login to my ac...,Account Login
2,3,My payment was declined while making a purchase,Payment Issue
3,4,The mobile application crashes when I open it,App Problem
4,5,I want to cancel my subscription plan,Subscription
5,6,My order has not arrived yet,Delivery Issue
6,7,I received a damaged product,Product Issue
7,8,Someone hacked my account and changed my password,Security
8,9,I need help updating my profile details,Account Management
9,10,The website is showing an unexpected error,Website Error

In [3]:
df.to_csv("support_tickets.csv", index=False)

print("support_tickets.csv created successfully")

support_tickets.csv created successfully

In [4]:
import pandas as pd

df = pd.read_csv("support_tickets.csv")

df.head()

,ticket_id,ticket_text,category
0,1,My internet connection is not working,Internet Issue
1,2,I forgot my password and cannot login to my ac...,Account Login
2,3,My payment was declined while making a purchase,Payment Issue
3,4,The mobile application crashes when I open it,App Problem
4,5,I want to cancel my subscription plan,Subscription

In [1]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Zero-shot LLM model loaded successfully")

ModuleNotFoundError: No module named 'transformers'

In [2]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Zero-shot LLM model loaded successfully")}

SyntaxError: unmatched '}' (2631818886.py, line 8)

In [3]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Zero-shot LLM model loaded successfully")

ModuleNotFoundError: No module named 'transformers'

In [4]:
import sys
print(sys.executable)

e:\Users\Yoga 460\anaconda3\python.exe

In [1]:
import sys
print(sys.executable)

D:\Task5 Auto Tagging Support Tickets Using LLM\venv\Scripts\python.exe

In [2]:
import transformers
print(transformers.__version__)

5.13.0

In [ ]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Zero-shot LLM model loaded successfully")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B