In [5]:
import pandas as pd

In [6]:
train_df = pd.read_csv("data/train.csv", header=None)

In [7]:
test_df = pd.read_csv("data/test.csv", header=None)

In [8]:
train_df.head()

,0,1,2
0,Class Index,Title,Description
1,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
2,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
3,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
4,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...

In [9]:
train_df.columns = ["label", "title", "text"]
test_df.columns = ["label", "title", "text"]

In [10]:
train_df.head()

,label,title,text
0,Class Index,Title,Description
1,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
2,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
3,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
4,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...

In [11]:
print("Train Shape:", train_df.shape)
print("Test Shape:", test_df.shape)

Train Shape: (120001, 3)
Test Shape: (7601, 3)

In [12]:
train_df.isnull().sum()

label    0
title    0
text     0
dtype: int64

In [13]:
train_df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")

In [14]:
train_df.head()

,Class Index,Title,Description
0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli..."
1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...
2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...
3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...
4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco..."

In [15]:
print(train_df.shape)
print(test_df.shape)

(120000, 3)
(7600, 3)

In [17]:
print(train_df.columns)

Index(['Class Index', 'Title', 'Description'], dtype='str')

In [18]:
train_df["text"] = train_df["Title"] + " " + train_df["Description"]
test_df["text"] = test_df["Title"] + " " + test_df["Description"]

In [19]:
train_df = train_df[["text", "Class Index"]]
test_df = test_df[["text", "Class Index"]]

In [20]:
train_df.rename(columns={"Class Index": "label"}, inplace=True)
test_df.rename(columns={"Class Index": "label"}, inplace=True)

In [21]:
train_df.head()

                                                text  label
0  Wall St. Bears Claw Back Into the Black (Reute...      3
1  Carlyle Looks Toward Commercial Aerospace (Reu...      3
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      3
3  Iraq Halts Oil Exports from Main Southern Pipe...      3
4  Oil prices soar to all-time record, posing new...      3

In [22]:
train_df["label"].value_counts()

label
3    30000
4    30000
2    30000
1    30000
Name: count, dtype: int64

In [23]:
train_df["label"] = train_df["label"] - 1
test_df["label"] = test_df["label"] - 1

In [24]:
train_df["label"].value_counts()

label
2    30000
3    30000
1    30000
0    30000
Name: count, dtype: int64

In [25]:
train_df["label"].value_counts()

label
2    30000
3    30000
1    30000
0    30000
Name: count, dtype: int64

In [26]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

D:\Task1 News Topic Classifier Using BERT\venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Yoga 460\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [27]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

In [28]:
from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

In [29]:
train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/120000 [00:00<?, ? examples/s]

Map:   0%|          | 0/7600 [00:00<?, ? examples/s]

In [30]:
train_dataset

Dataset({
    features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 120000
})

In [31]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=4
)

model.safetensors: reconstructing file:   0%|          |  0.00B /  440MB

model.safetensors: downloading bytes:           |  0.00B

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())